### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by patdohere**
Generalize LED commands in README.md

### CODE REVIEW

**Comment by morrownr** [comment]
That is a good idea. Wish I had though of it.

Hey, would you like to make a script to automate the process?

**Comment by patdohere** [comment]
Was thinking the same thing, but didn't know how to check if the devices is part of AWUS036ACM.  Didn't want to flip the LED bit unless we know its the correct adapter.  Open to ideas around this.

**Comment by morrownr** [comment]
> didn't know how to check if the devices is part of AWUS036ACM

This is not an issue with this specific adapter. This is an issue with the device driver so it affects all adapters with the mt7612u chipset. I have tested several.

Let me suggest this: I can add a file here to start things... just basically an empty file so that you can have some to do PRs with. I could call it something like `led_ctrl_7612u.sh` then you can start adding things to it as you have time and I can test and make suggestions as I have time. What do you think?

Nick

**Comment by patdohere** [comment]
Sounds good I'll work with it from there

**Pull request merged**
